compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,3,6
machine_rank: 1
main_process_ip: 143.248.49.62
main_process_port: 53773
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

# 143.248.49.62
# 53773

# 143.248.49.126
# 57646

# 143.248.49.128
# 53277