#!/usr/bin/env bash

# VLP - Stage1 (Pretrained)
n_gpu=1
image_bath=4
test_batch=1

# CuLLaVOPipeline
accelerate launch --config_file configs/accel/node_ddp_accel.yaml \
                    entry.py train \
                    --conf_files configs/cullavo_step1.yaml \
                    --overrides \
                    WANDB True \
                    PIPELINE CuLLaVOPipeline\
                    COCO.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
                    COCO.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
                    COCO.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
                    VLP.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
                    VLP.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
                    VLP.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
                    REF.TEST.BATCH_SIZE_TOTAL $n_gpu \
                    VQA.TEST.BATCH_SIZE_TOTAL $n_gpu \
                    # IMAGENET.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch))\
                    ADE20K.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \