#!/usr/bin/env bash

# VLP - Stage1 (Pretrained)
GPU_DEVICE="0,1,2,3"
length=${#GPU_DEVICE}
n_gpu=$(((length+1)/2))
image_bath=1
test_batch=1

accelerate launch --config_file configs/accel/ddp_accel.yaml \
            --num_processes=$n_gpu \
            lbk_entry.py eval \
            --conf_files configs/vl_test.yaml \
            --overrides \
            WANDB False \
            COCO.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
            COCO.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
            COCO.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
            VLP.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
            VLP.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
            VLP.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
            REF.TEST.BATCH_SIZE_TOTAL $n_gpu \
            VQA.TEST.BATCH_SIZE_TOTAL $n_gpu \
            ADE20K.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
            WEIGHT True \
            RESUME_FROM /mnt/ssd/lbk-cvpr/checkpoints/xdecoder_focall_last.pt